// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bevjbufbmxqezpidzfxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJldmpidWZibXhxZXpwaWR6Znh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzU4NDcsImV4cCI6MjA1ODgxMTg0N30.Dp6tdLvC0OK8j4jkCzDw9tLGDAMftgMPWYtFIp1fMSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);